[languages]
    [languages.en]
        disabled = false
        languageCode = 'en-US'
        languageNameShort = 'en'
        languageFlag = 'US'
        languageName = 'English'
        weight = 1
        [languages.en.menu]
        [languages.en.params]
            displayName = "EN"
            homepage.showMoreLinkDest= "/blog/en/posts"
    [languages.ko]
        disabled = false
        languageCode = 'ko-KR'
        languageNameShort = 'kr'
        languageFlag = 'KR'
        languageName = 'Korean'
        weight = 2
        title = "트리플영"
        [languages.ko.menu]
        [languages.ko.params]
            displayName = "KO"
            homepage.showMoreLinkDest= "/blog/ko/posts"
    [languages.ja]
        disabled = false
        languageCode = 'ja-JP'
        languageNameShort = 'ja'
        languageFlag = 'JP'
        languageName = 'Japan'
        weight = 3
        [languages.ja.menu]
        [languages.ja.params]
            displayName = "JA"
            homepage.showMoreLinkDest= "/blog/ja/posts"







# robots.txt
enableRobotsTXT = true

summaryLength = 30

buildDrafts = false
paginate = 100

buildFuture = false


[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
googleAnalytics = "G-V13F66S3ZN"


[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'
    tutorials = '/training/:slug/'
  [permalinks.section]
    posts = '/posts/'
    tutorials = '/training/'
  [permalinks.term]
    tags = '/:slug/'