[languages]
    [languages.en]
        disabled = false
        languageCode = 'en-US'
        languageNameShort = 'en'
        languageFlag = 'US'
        languageName = 'English'
        weight = 1
        [languages.en.menu]
        [languages.en.params]
            displayName = "EN"
            homepage.showMoreLinkDest= "/blog/en/posts"
    [languages.ko]
        disabled = false
        languageCode = 'ko-KR'
        languageNameShort = 'kr'
        languageFlag = 'KR'
        languageName = 'Korean'
        weight = 2
        title = "트리플영"
        [languages.ko.menu]
        [languages.ko.params]
            displayName = "KO"
            homepage.showMoreLinkDest= "/blog/ko/posts"
    [languages.ja]
        disabled = false
        languageCode = 'ja-JP'
        languageNameShort = 'ja'
        languageFlag = 'JP'
        languageName = 'Japan'
        weight = 3
        [languages.ja.menu]
        [languages.ja.params]
            displayName = "JA"
            homepage.showMoreLinkDest= "/blog/ja/posts"

article.showRelatedContent = true
article.showTableOfContents = true