colorScheme = "blowfish"
mainSections = ["posts"]
homepage.layout = "page"
homepage.showRecent  = true
firebase.apiKey = "AIzaSyB-kPBeiIUcGr4cLjeRFSX_KxG9dAifX1M"
firebase.authDomain = "blog-c3555.firebaseapp.com"
firebase.projectId = "blog-c3555"
firebase.storageBucket = "blog-c3555.appspot.com"
firebase.messagingSenderId = "723303301054"
firebase.appId = "1:723303301054:web:78315ee34805c190a1c3ef"
firebase.measurementId = "G-V2EB1Q4KTV"

article.showViews = true
article.showLikes = true
list.showViews = true 
list.showLikes = true 
taxonomy.showViews = true
taxonomy.showLikes = true
term.showViews = true
term.showLikes = true
homepage.cardView = true
homepage.layoutBackgroundBlur = true 
article.showTaxonomies=true
article.showAuthorsBadges=true 
list.showHero = true
homepage.showMoreLink = true
homepage.showMoreLinkDest= "/blog/en/posts"
article.showWordCount = false
article.showComments = true
list.showTableOfContents = true 