googleAnalytics = "G-V13F66S3ZN"
# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
[related]
  includeNewer = true
  threshold = 20
  toLower = false
[[related.indices]]
    applyFilter = false
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 80