# config/_default/menus.toml

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

[[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
[[main]]
  pre = "깃허브"
  name = "GitHub"
  url = "https://github.com/dudnjsckrgo"
  weight = 30
